FROM python:3.10.6-slim-buster

WORKDIR /backend

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8081

RUN useradd -m backend

USER backend

CMD ["python3", "api_server.py"]