# Use a specific Python slim image
FROM python:3.10.6-slim-buster

WORKDIR /backend


COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN useradd -m backend
USER backend

EXPOSE 8000


CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
