export const jobPosts = [
  {
    id: 1,
    title: "Software Engineering Intern – AI",
    company: "Nebula Systems",
    location: "San Francisco, CA (On-site)",
    posted: "2 days ago",
    applicants: 36,
    status: "Active",
    summary:
      "Join Nebula's AI team to build and ship real-world LLM-based tools with a strong engineering focus.",
    description:
      "Join Nebula's AI team and help build powerful tools that serve thousands of users. You'll be part of a fast-moving, high-impact engineering group that focuses on real-world AI applications. This role gives you the chance to work with cutting-edge LLM technologies, build production-grade systems, and collaborate across multiple disciplines within the company.",
    responsibilities: [
      "Build and enhance AI-driven features using LLMs and modern backend systems",
      "Collaborate with engineers, designers, and PMs on user-facing tools",
      "Write clean, tested, and maintainable code across the stack"
    ],
    qualifications: [
      "Pursuing a degree in Computer Science or related field",
      "Familiarity with Python, TypeScript, or Node.js",
      "Strong problem-solving skills and interest in AI"
    ],
    bonus: [
      "Experience with prompt engineering or vector databases",
      "Contributions to open-source AI projects"
    ],
    technologies: ["Python", "TypeScript", "Node.js", "LLMs", "Vector DBs"]
  },
  {
    id: 2,
    title: "Frontend Developer Intern",
    company: "Nebula Systems",
    location: "Remote (US)",
    posted: "3 days ago",
    applicants: 24,
    status: "Active",
    summary:
      "Craft clean, responsive UIs for AI dashboards using React and collaborate with designers and engineers.",
    description:
      "Nebula Systems is seeking a frontend-focused intern to help elevate the user experience of our core dashboard and AI insights tools. You'll work closely with design and product to bring interfaces to life. The ideal candidate is passionate about clean, accessible UI, and has a strong eye for detail and interaction design.",
    responsibilities: [
      "Implement responsive, accessible UIs using React and Tailwind CSS",
      "Collaborate with design to refine UX flows",
      "Participate in code reviews and frontend architecture discussions"
    ],
    qualifications: [
      "Experience with React, HTML/CSS, and JavaScript",
      "Interest in UI/UX design principles",
      "Good communication and team collaboration skills"
    ],
    bonus: [
      "Familiarity with animation libraries or testing frameworks",
      "Understanding of performance optimization in SPAs"
    ],
    technologies: ["React", "JavaScript", "Tailwind CSS", "UI/UX", "Testing"]
  },
  {
    id: 3,
    title: "Product Management Intern",
    company: "Nebula Systems",
    location: "San Francisco, CA (Hybrid)",
    posted: "5 days ago",
    applicants: 42,
    status: "Active",
    summary:
      "Support AI product development by writing specs, analyzing metrics, and collaborating across teams.",
    description:
      "Work directly with product leaders at Nebula Systems to define features, analyze metrics, and shape the future of AI-powered tools. This is a fast-paced role where you'll learn what it takes to manage and ship impactful software. You'll own project lifecycles, partner with design and engineering, and build the skills needed for a product career in tech.",
    responsibilities: [
      "Write product specs and collaborate with engineering on implementation",
      "Define success metrics and track product health",
      "Conduct market research and competitive analysis"
    ],
    qualifications: [
      "Currently pursuing a degree in Business, CS, or related",
      "Strong written and verbal communication skills",
      "Comfort working in fast-paced and ambiguous environments"
    ],
    bonus: [
      "Previous internship or project experience in product or design",
      "Proficiency in tools like Figma, Notion, or Airtable"
    ],
    technologies: ["Figma", "Notion", "Airtable", "Analytics", "Product Strategy"]
  }
];

export const detailedCandidates = [
  {
    id: "cand-1",
    name: "Sarah Johnson",
    position: "Senior Frontend Developer",
    email: "sarah.johnson@example.com",
    phone: "111-222-3333",
    location: "San Francisco, CA",
    experience: "7+ years",
    experienceYears: 7,
    experienceLevel: "Senior",
    education: "BS in Computer Science, Stanford University",
    appliedDate: "2024-07-10",
    overallScore: 94,
    decision: "HIRE",
    confidence: 0.94,
    skills: [
      { name: "React", score: 98, required: true },
      { name: "TypeScript", score: 95, required: true },
      { name: "Next.js", score: 90, required: true },
      { name: "GraphQL", score: 85, required: false },
      { name: "Figma", score: 80, required: false },
    ],
    summary: "Exceptional senior frontend developer with a proven track record of leading teams and delivering high-quality, scalable applications. Expertise in modern JavaScript frameworks and a passion for UI/UX.",
    strengths: ["Expert in React & TypeScript", "Strong leadership and mentoring skills", "Proven ability to improve performance", "Excellent UI/UX sensibility"],
    concerns: ["Limited exposure to Python backend", "No direct experience with our internal tooling"],
    recommendation: "Top-tier candidate. Strong hire for a lead frontend position. Her skills and experience are a perfect match for our current needs.",
    keyFactors: ["Technical Expertise", "Leadership", "Performance Optimization"],
    achievements: ["Led the redesign of a major e-commerce platform, increasing conversion by 20%", "Reduced page load time by 50% for a high-traffic web app", "Mentored a team of 5 junior developers"],
    skillMatches: ["React", "TypeScript", "Next.js"],
    skillGaps: ["Internal Tooling"],
    experienceMatch: "Excellent",
    analysis: "Sarah is an outstanding candidate. Her deep expertise in our core frontend technologies, combined with her leadership experience, makes her an ideal fit. She can be expected to ramp up quickly and make an immediate impact.",
    transcript: [
        { agent_name: "ResumeParserAgent", position: "evaluation", content: "Analyzed resume for Sarah Johnson. 7 years experience in frontend, strong with React, TypeScript, Next.js. Clear leadership roles and performance metrics.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "Her experience is a perfect match. The 20% conversion increase and 50% load time reduction are concrete examples of her impact. She's a leader.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "Her backend skills are not mentioned. We need engineers who can work across the stack. The lack of Python is a potential issue.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "This is a frontend role, and her expertise is elite. We can't pass on a candidate this strong for a minor backend gap. She can learn our systems.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "Is she a culture fit? The resume seems very focused on large corporate environments. We are a fast-moving startup.", details: {} },
    ]
  },
  {
    id: "cand-2",
    name: "David Kim",
    position: "Senior Backend Engineer",
    email: "david.kim@example.com",
    phone: "222-333-4444",
    location: "New York, NY",
    experience: "8+ years",
    experienceYears: 8,
    experienceLevel: "Senior",
    education: "MS in Computer Engineering, Carnegie Mellon",
    appliedDate: "2024-07-09",
    overallScore: 92,
    decision: "HIRE",
    confidence: 0.92,
    skills: [
        { name: "Python", score: 96, required: true },
        { name: "Django", score: 90, required: false },
        { name: "PostgreSQL", score: 94, required: true },
        { name: "AWS", score: 91, required: true },
        { name: "Terraform", score: 88, required: true },
    ],
    summary: "Veteran backend engineer specializing in distributed systems and cloud infrastructure. Highly proficient in Python and AWS, with a strong focus on scalability and reliability.",
    strengths: ["Expert in Python and AWS", "Deep knowledge of database architecture", "Experience with infrastructure as code (Terraform)", "Proven ability to scale systems"],
    concerns: ["Less experience with modern frontend frameworks", "Primarily focused on backend infrastructure"],
    recommendation: "Excellent candidate for a senior backend or infrastructure role. His skills are a strong match for our needs in building a scalable backend.",
    keyFactors: ["Cloud Architecture", "Database Management", "Scalability"],
    achievements: ["Architected a multi-region AWS infrastructure serving millions of users", "Optimized database performance, reducing query latency by 70%", "Led a team to adopt Terraform for infrastructure management"],
    skillMatches: ["Python", "PostgreSQL", "AWS", "Terraform"],
    skillGaps: ["Frontend Frameworks"],
    experienceMatch: "Excellent",
    analysis: "David's profile is a perfect fit for a senior backend role. His extensive experience with AWS and Python, coupled with his achievements in scalability and performance, would be a massive asset.",
    transcript: [
        { agent_name: "ResumeParserAgent", position: "evaluation", content: "Parsing David Kim's resume. 8 years backend experience. Expertise in Python, AWS, and Terraform. Notable achievements in scaling and database optimization.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "The 70% query latency reduction is a huge indicator of his skills. His AWS and Terraform experience is exactly what we're looking for to scale our infrastructure.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "He seems purely backend-focused. Will he be able to collaborate effectively with our full-stack teams? There's a risk of creating knowledge silos.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "For a senior backend role, this level of specialization is a strength, not a weakness. He will set the standard for our backend architecture.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "He's coming from very large tech companies. Can he adapt to our startup's pace and resource constraints? It's a different world.", details: {} },
    ]
  },
  {
    id: "cand-3",
    name: "Michael Chen",
    position: "Backend Engineer",
    email: "michael.chen@example.com",
    phone: "333-444-5555",
    location: "Seattle, WA",
    experience: "4 years",
    experienceYears: 4,
    experienceLevel: "Mid-Level",
    education: "BS in Informatics, University of Washington",
    appliedDate: "2024-07-12",
    overallScore: 88,
    decision: "HIRE",
    confidence: 0.88,
    skills: [
        { name: "Go", score: 92, required: true },
        { name: "Kubernetes", score: 85, required: true },
        { name: "gRPC", score: 88, required: false },
        { name: "Prometheus", score: 82, required: false },
        { name: "Docker", score: 90, required: true },
    ],
    summary: "Pragmatic backend engineer with a strong background in Go and cloud-native technologies like Kubernetes. Passionate about building resilient, observable systems.",
    strengths: ["Proficient in Go", "Strong experience with Kubernetes and Docker", "Focus on system observability (Prometheus)", "Good problem-solving skills"],
    concerns: ["Lacks experience with large-scale data pipelines", "Limited experience with serverless architectures"],
    recommendation: "Solid hire for a mid-level backend position. His Go and Kubernetes skills are highly valuable for our microservices architecture.",
    keyFactors: ["Go Proficiency", "Kubernetes", "Microservices"],
    achievements: ["Co-developed a gRPC-based microservice handling 1M daily requests", "Built and maintained Kubernetes deployment pipelines", "Improved system monitoring, reducing downtime by 30%"],
    skillMatches: ["Go", "Kubernetes", "Docker"],
    skillGaps: ["Serverless", "Data Pipelines"],
    experienceMatch: "Good",
    analysis: "Michael is a strong mid-level engineer whose skills in Go and Kubernetes align perfectly with our backend strategy. He has a solid foundation in building and maintaining microservices.",
    transcript: [
        { agent_name: "ResumeParserAgent", position: "evaluation", content: "Michael Chen, 4 years experience. Strong in Go, Kubernetes, Docker. Achievements in microservices and monitoring.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "His Go and Kubernetes skills are exactly what we need for our new microservices. The 30% downtime reduction is impressive.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "He's more of a generalist. Does he have the deep database knowledge we need for the core services team?", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "A mid-level role doesn't require deep specialization yet. His cloud-native skills are more valuable at this stage. He's a great fit.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "Only 4 years of experience. Are we sure he can handle the complexity of our system without significant hand-holding?", details: {} },
    ]
  },
  {
    id: "cand-4",
    name: "Emily Rodriguez",
    position: "Full Stack Developer",
    email: "emily.rodriguez@example.com",
    phone: "444-555-6666",
    location: "Austin, TX",
    experience: "5 years",
    experienceYears: 5,
    experienceLevel: "Mid-Level",
    education: "BS in Computer Science, University of Texas at Austin",
    appliedDate: "2024-07-11",
    overallScore: 85,
    decision: "HIRE",
    confidence: 0.85,
    skills: [
        { name: "Node.js", score: 88, required: true },
        { name: "React", score: 90, required: true },
        { name: "TypeScript", score: 85, required: true },
        { name: "MongoDB", score: 80, required: false },
        { name: "Express", score: 86, required: false },
    ],
    summary: "Versatile full-stack developer with a balanced skill set in both frontend and backend development. Thrives in collaborative, fast-paced environments.",
    strengths: ["Strong proficiency in the MERN stack", "Excellent problem-solver", "Good communication skills", "Proven ability to ship features end-to-end"],
    concerns: ["Lacks experience with large-scale, distributed systems", "No exposure to our primary cloud provider (AWS)"],
    recommendation: "Good mid-level full-stack hire. Her ability to work across the stack is a great asset for a product-focused team.",
    keyFactors: ["Full-Stack Capability", "Node.js", "React"],
    achievements: ["Shipped 10+ features for a SaaS product from ideation to deployment", "Led a project to migrate a legacy codebase to TypeScript", "Received 'Team Player of the Quarter' award"],
    skillMatches: ["Node.js", "React", "TypeScript"],
    skillGaps: ["AWS", "Distributed Systems"],
    experienceMatch: "Good",
    analysis: "Emily is a capable full-stack developer who can contribute across our entire stack. Her experience with TypeScript and the MERN stack is very relevant. She would be a productive member of any of our feature teams.",
    transcript: [
        { agent_name: "ResumeParserAgent", position: "evaluation", content: "Emily Rodriguez, 5 years full-stack. Strong MERN and TypeScript. Shipped over 10 features end-to-end.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "Her full-stack capabilities are a huge plus. The TypeScript migration project shows initiative and strong technical skills. She can own features completely.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "She has no AWS experience, which is a major part of our infrastructure. The learning curve will be steep.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "A smart developer can learn a cloud provider. Her core skills in Node.js and React are much harder to find. We should hire for aptitude.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "All of her experience is with MongoDB. We use PostgreSQL exclusively. This is a significant database knowledge gap.", details: {} },
    ]
  },
  {
    id: "cand-5",
    name: "Alex Williams",
    position: "AI/ML Engineer",
    email: "alex.williams@example.com",
    phone: "555-666-7777",
    location: "Boston, MA",
    experience: "6 years",
    experienceYears: 6,
    experienceLevel: "Senior",
    education: "PhD in Machine Learning, MIT",
    appliedDate: "2024-07-08",
    overallScore: 96,
    decision: "HIRE",
    confidence: 0.96,
    skills: [
        { name: "Python", score: 99, required: true },
        { name: "TensorFlow", score: 95, required: true },
        { name: "PyTorch", score: 92, required: true },
        { name: "Scikit-learn", score: 94, required: false },
        { name: "Keras", score: 90, required: false },
    ],
    summary: "Accomplished AI/ML engineer with a PhD and extensive experience in developing and deploying production-level machine learning models. Specializes in NLP and computer vision.",
    strengths: ["Deep theoretical and practical knowledge of ML", "Expert in Python and major ML frameworks", "Experience with MLOps and production deployment", "Published researcher"],
    concerns: ["Less experience with frontend development", "More research-focused than product-focused"],
    recommendation: "Exceptional candidate for a senior AI/ML role. His expertise would significantly accelerate our AI development efforts. A clear hire.",
    keyFactors: ["ML Expertise", "Python", "Production Experience"],
    achievements: ["Developed a novel NLP model that improved accuracy by 15% over state-of-the-art", "Published 3 papers in top-tier AI conferences", "Built the deployment pipeline for a real-time computer vision system"],
    skillMatches: ["Python", "TensorFlow", "PyTorch"],
    skillGaps: ["Frontend Development"],
    experienceMatch: "Excellent",
    analysis: "Alex's profile is stellar. His PhD from MIT and extensive experience with core ML frameworks make him a rare find. He has both research and production experience, which is incredibly valuable.",
    transcript: [
        { agent_name: "ResumeParserAgent", position: "evaluation", content: "Alex Williams. PhD in ML from MIT. 6 years experience. Expert in Python, TensorFlow, PyTorch. Published researcher with production deployment experience.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "A PhD from MIT and publications at top conferences is all we need to know. His skills are world-class. He can lead our AI research.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "Is his experience too academic? We need to ship products, not just write papers. Can he work on tight product deadlines?", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "He built a real-time deployment pipeline. That shows he understands production needs. This is the perfect blend of research and engineering.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "His salary expectations will be very high. We need to be sure we can provide him with challenging enough work to justify the cost.", details: {} },
    ]
  },
  {
    id: "cand-6",
    name: "Jessica Brown",
    position: "UI/UX Designer",
    email: "jessica.brown@example.com",
    phone: "666-777-8888",
    location: "Los Angeles, CA",
    experience: "5 years",
    experienceYears: 5,
    experienceLevel: "Mid-Level",
    education: "BA in Graphic Design, UCLA",
    appliedDate: "2024-07-15",
    overallScore: 89,
    decision: "HIRE",
    confidence: 0.89,
    skills: [
        { name: "Figma", score: 98, required: true },
        { name: "Sketch", score: 90, required: false },
        { name: "Adobe XD", score: 85, required: false },
        { name: "User Research", score: 92, required: true },
        { name: "Prototyping", score: 95, required: true },
    ],
    summary: "Creative and user-centric UI/UX designer with a strong portfolio of intuitive and beautiful designs for web and mobile applications.",
    strengths: ["Expert in Figma", "Strong user research skills", "Excellent prototyping and wireframing ability", "Collaborates effectively with engineers and PMs"],
    concerns: ["Less experience with complex data visualization", "Has not worked in a B2B SaaS environment before"],
    recommendation: "Strong hire for a UI/UX role. Her portfolio is excellent and her user-centric approach is exactly what we need.",
    keyFactors: ["Figma", "User Research", "Portfolio"],
    achievements: ["Led the design of a mobile app that was featured on the App Store", "Conducted user research that led to a 40% improvement in user satisfaction", "Created and maintained a design system for a team of 20+"],
    skillMatches: ["Figma", "User Research", "Prototyping"],
    skillGaps: ["Data Visualization"],
    experienceMatch: "Good",
    analysis: "Jessica is a very talented designer. Her expertise in Figma and her strong focus on user research would be a great addition to our product team. She has a proven ability to deliver high-quality and impactful designs.",
    transcript: [
        { agent_name: "ResumeParserAgent", position: "evaluation", content: "Jessica Brown, 5 years UI/UX. Expert in Figma, strong in user research and prototyping. App Store feature and 40% user satisfaction increase are key achievements.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "Her portfolio is stunning. The design system experience is a huge plus for team scalability. The 40% satisfaction improvement is a great metric.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "Our product is heavy on data visualization. Her portfolio doesn't show much experience in that area. It's a key part of the role.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "A strong designer can learn a new domain. Her fundamentals in user research and prototyping are what matters. She can handle data viz.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "All her experience is in consumer apps. Does she understand the complexities and user needs of a B2B SaaS product?", details: {} },
    ]
  },
  {
    id: "cand-7",
    name: "Chris Lee",
    position: "DevOps Engineer",
    email: "chris.lee@example.com",
    phone: "777-888-9999",
    location: "Chicago, IL",
    experience: "7 years",
    experienceYears: 7,
    experienceLevel: "Senior",
    education: "BS in Information Technology, University of Illinois",
    appliedDate: "2024-07-13",
    overallScore: 91,
    decision: "HIRE",
    confidence: 0.91,
    skills: [
        { name: "AWS", score: 95, required: true },
        { name: "Jenkins", score: 88, required: false },
        { name: "Ansible", score: 85, required: false },
        { name: "Docker", score: 94, required: true },
        { name: "Kubernetes", score: 92, required: true },
    ],
    summary: "Experienced DevOps engineer with a deep understanding of CI/CD, containerization, and cloud infrastructure. Passionate about automation and improving developer productivity.",
    strengths: ["Expert in AWS and Kubernetes", "Strong background in CI/CD automation", "Proficient with Docker", "Focus on developer productivity and infrastructure reliability"],
    concerns: ["Less experience with Google Cloud Platform", "More focused on infrastructure than application-level performance"],
    recommendation: "Strong hire for a senior DevOps role. His experience with our core infrastructure technologies is a great fit.",
    keyFactors: ["AWS", "Kubernetes", "CI/CD"],
    achievements: ["Built a CI/CD pipeline from scratch, reducing deployment time from hours to minutes", "Managed a large-scale Kubernetes cluster with 99.99% uptime", "Automated infrastructure provisioning, saving hundreds of developer hours"],
    skillMatches: ["AWS", "Kubernetes", "Docker"],
    skillGaps: ["GCP"],
    experienceMatch: "Excellent",
    analysis: "Chris is a highly skilled DevOps engineer. His expertise in AWS, Kubernetes, and CI/CD automation aligns perfectly with our infrastructure needs. He would be instrumental in improving our deployment processes and overall reliability.",
    transcript: [
        { agent_name: "ResumeParserAgent", position: "evaluation", content: "Chris Lee, 7 years DevOps. Expert in AWS, K8s, Docker. Key achievements in CI/CD and automation.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "Reducing deployment time from hours to minutes is a game-changer. His Kubernetes and AWS experience is exactly what we need for our infra team.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "We are considering a multi-cloud strategy. His lack of GCP experience could be a problem in the long run.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "The principles of DevOps and cloud management are transferable. An expert in one cloud can learn another. His current skills are what we need now.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "He seems very focused on pure infra. Does he have enough experience with application monitoring and performance tuning?", details: {} },
    ]
  },
  {
    id: "cand-8",
    name: "Maria Garcia",
    position: "Product Manager",
    email: "maria.garcia@example.com",
    phone: "888-999-0000",
    location: "Miami, FL",
    experience: "9 years",
    experienceYears: 9,
    experienceLevel: "Senior",
    education: "MBA, University of Miami",
    appliedDate: "2024-07-14",
    overallScore: 93,
    decision: "HIRE",
    confidence: 0.93,
    skills: [
        { name: "Agile", score: 98, required: true },
        { name: "Jira", score: 95, required: true },
        { name: "Roadmapping", score: 96, required: true },
        { name: "Market Analysis", score: 90, required: false },
        { name: "Scrum", score: 94, required: false },
    ],
    summary: "Seasoned product manager with a track record of launching successful B2B SaaS products. Data-driven and customer-focused, with excellent cross-functional leadership skills.",
    strengths: ["Expert in Agile and Scrum methodologies", "Strong product strategy and roadmapping skills", "Data-driven decision maker", "Excellent communication and leadership"],
    concerns: ["Less hands-on technical experience", "Has not worked in an AI-first company before"],
    recommendation: "Excellent hire for a senior product manager role. Her experience in B2B SaaS and her data-driven approach are a perfect fit for our product organization.",
    keyFactors: ["Product Strategy", "B2B SaaS Experience", "Agile"],
    achievements: ["Led the launch of a new product that generated $5M in ARR in its first year", "Increased user engagement by 30% through data-driven feature enhancements", "Managed a product backlog for a team of 15 engineers"],
    skillMatches: ["Agile", "Jira", "Roadmapping"],
    skillGaps: ["AI Product Experience"],
    experienceMatch: "Excellent",
    analysis: "Maria is a very experienced product manager. Her success in launching and growing B2B SaaS products is highly relevant. She has the strategic thinking and leadership skills to make a big impact on our product roadmap.",
    transcript: [
        { agent_name: "ResumeParserAgent", position: "evaluation", content: "Maria Garcia, 9 years PM. B2B SaaS focus. Launched product to $5M ARR. Increased engagement by 30%. Expert in Agile and roadmapping.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "The $5M ARR launch is a massive signal. She knows how to build and ship successful products. Her data-driven approach to increasing engagement is exactly the mindset we need.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "She has no experience with AI products. The learning curve for understanding the technology and user expectations will be steep. This is a big risk.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "A great PM can learn any domain. The core skills of product management are what matter, and she has them in spades. She'll learn the AI space.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "Her background is in larger, more established companies. Can she handle the ambiguity and pace of an early-stage startup?", details: {} },
    ]
  },
  {
    id: "cand-9",
    name: "Daniel Martinez",
    position: "Data Scientist",
    email: "daniel.martinez@example.com",
    phone: "999-000-1111",
    location: "Denver, CO",
    experience: "4 years",
    experienceYears: 4,
    experienceLevel: "Mid-Level",
    education: "MS in Data Science, University of Denver",
    appliedDate: "2024-07-16",
    overallScore: 86,
    decision: "HIRE",
    confidence: 0.86,
    skills: [
        { name: "Python", score: 94, required: true },
        { name: "R", score: 85, required: false },
        { name: "SQL", score: 92, required: true },
        { name: "Tableau", score: 88, required: false },
        { name: "Machine Learning", score: 85, required: true },
    ],
    summary: "Analytical data scientist with a strong foundation in statistical analysis, machine learning, and data visualization. Skilled at translating data into actionable insights.",
    strengths: ["Strong in Python and SQL", "Good understanding of machine learning concepts", "Excellent data visualization skills", "Experience with statistical analysis"],
    concerns: ["Less experience with production-level data pipelines", "Limited exposure to big data technologies like Spark"],
    recommendation: "Solid hire for a mid-level data scientist role. His analytical and visualization skills would be a great asset to our analytics team.",
    keyFactors: ["Python", "SQL", "Machine Learning"],
    achievements: ["Built a predictive model that improved marketing ROI by 25%", "Created a series of Tableau dashboards that became the source of truth for business KPIs", "Uncovered a key insight that led to a new product feature"],
    skillMatches: ["Python", "SQL", "Machine Learning"],
    skillGaps: ["Spark", "Production Data Pipelines"],
    experienceMatch: "Good",
    analysis: "Daniel is a capable data scientist with a good mix of statistical, machine learning, and visualization skills. He can clearly derive valuable insights from data and communicate them effectively. He's a great fit for our data team.",
    transcript: [
        { agent_name: "ResumeParserAgent", position: "evaluation", content: "Daniel Martinez, 4 years Data Science. MS degree. Strong Python, SQL, ML. Key achievement is a predictive model improving ROI by 25%.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "Improving marketing ROI by 25% is a quantifiable impact. His ability to build predictive models and create insightful dashboards is exactly what we need.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "His experience with big data technologies like Spark is non-existent. Our datasets are massive. Can he handle the scale?", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "His core Python and SQL skills are strong. He can learn Spark. We need someone who can build models and create insights, and he has proven he can do that.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "He's only worked on the analytics side. Does he have any experience with putting models into a production software environment?", details: {} },
    ]
  },
  {
    id: "cand-10",
    name: "Olivia White",
    position: "Frontend Developer",
    email: "olivia.white@example.com",
    phone: "000-111-2222",
    location: "Portland, OR",
    experience: "3 years",
    experienceYears: 3,
    experienceLevel: "Junior-Mid",
    education: "BS in Web Design, University of Oregon",
    appliedDate: "2024-07-17",
    overallScore: 82,
    decision: "CONSIDER",
    confidence: 0.82,
    skills: [
        { name: "Vue.js", score: 90, required: false },
        { name: "JavaScript", score: 92, required: true },
        { name: "CSS", score: 88, required: true },
        { name: "HTML", score: 95, required: true },
        { name: "Webpack", score: 80, required: false },
    ],
    summary: "Passionate frontend developer with a keen eye for design and a strong foundation in modern JavaScript. Eager to grow and contribute in a collaborative team environment.",
    strengths: ["Strong JavaScript and CSS fundamentals", "Good design sense", "Quick learner and highly motivated", "Experience with Vue.js"],
    concerns: ["No experience with React or TypeScript", "Limited experience with large, complex applications", "Fewer years of professional experience"],
    recommendation: "A promising junior candidate. While she lacks experience with our specific stack (React/TS), her strong fundamentals and motivation make her worth considering for a junior role with mentorship.",
    keyFactors: ["JavaScript Fundamentals", "Design Sense", "Growth Potential"],
    achievements: ["Rebuilt the marketing website for a local business, increasing traffic by 30%", "Contributed to an open-source Vue.js component library", "Consistently praised for clean and maintainable code"],
    skillMatches: ["JavaScript", "CSS", "HTML"],
    skillGaps: ["React", "TypeScript"],
    experienceMatch: "Fair",
    analysis: "Olivia has a solid foundation as a frontend developer. Her lack of React and TypeScript experience is a significant gap, but her strong JavaScript skills and design sense suggest she could learn quickly. She's a good candidate for a junior position where she can be mentored.",
    transcript: [
        { agent_name: "ResumeParserAgent", position: "evaluation", content: "Olivia White, 3 years experience. Focus on Vue.js, strong fundamentals in JS, CSS, HTML. Increased a site's traffic by 30%.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "Her fundamentals are strong, and the 30% traffic increase is a good sign. She's motivated and a quick learner. We can teach her React.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "The lack of React and TypeScript is a dealbreaker. We need someone who can be productive from day one. The cost of training her is too high.", details: {} },
        { agent_name: "ProHireAgent", position: "pro", content: "Hiring for potential is smart for building a long-term team. She's not a senior, she's a junior. We should have a path for developers like her.", details: {} },
        { agent_name: "AntiHireAgent", position: "anti", content: "Her experience is only with small marketing sites. Our application is a complex SaaS platform. It's a completely different level of engineering.", details: {} },
    ]
  }
];




